### ISSUE TITLE
Contacted Poheart thru reddit asking about FF version now its deleted?

### ISSUE THREAD

**Issue by wazerstar** [Poheart/FACEIT-HELPER#23]
So did you decide not to release Firefox version?, its a shame would really be loved in the FF community that also don't like chrome as their daily browser.

**Comment by Poheart** [comment]
I didn't deleted the add-ons from the Firefox store, they disapproved and removed it until we fixed what they wanted.
As i said before in the Reddit post , Firefox have a strict policy on approving add-ons, from files/libraries integrity, to images link sources control and privacy policy, plus long  reviewing time(~at least a month) for extensions to put up there.. 

So atm due to this extension is still developing and frequent changes/update , it is better to focus on Chrome/Opera version until we have a Stable version and port it to Firefox version.

**Comment by 43v6c3463** [comment]
Yeah seriously fuck mozilla and their stupid ass plugin requirements. I've edited a simple plugin myself to add just a few lines of code and when I tried to get it signed the site basically told me I have to completely rewrite the plugin from scratch to get it signed, yeah no thanks (and I'm not experienced enough to do that anyway). I'm using Firefox Developer Edition myself so it's not a problem since I'm able to run unsigned plugins but I have a lot of friends also using firefox who're using the release version and I can't share my modified plugin with them thanks to this crap. If you have a firefox port ready could you please share it here on github or somewhere even if you can't sign it so that atleast people running firefox developer edition could use it?

**Comment by Poheart** [comment]
I will make some changes to the current build soon so that you it will be compatible with chrome store foxified add-on  on Firefox

**Comment by 43v6c3463** [comment]
Thanks
